### ISSUE TITLE
Add expiration time to stopBot command

### ISSUE THREAD

**Issue by Flottegurke** [The-Bug-Bashers/VaGABfS#17]
after executing stopBot you need to execute stopBot yes in orde to stop the bot. there should after 2minutes you shuld have to start over again from the beginning.

- [x] add experation timer to stopBot command
- [x] update command reply to enshure the user gets informed about the expiration timer. 
- [x] add message to dilplay if time has expired
- [x] update wiki

**Comment by Dinkelbroetchen** [comment]
Sprich deutsch du Hurensohn
