### ISSUE TITLE
Update Setup-Guide

### ISSUE THREAD

**Issue by Flottegurke** [The-Bug-Bashers/VaGABfS#19]
The [Setup-Guide](https://github.com/The-Bug-Bashers/VaGABfS/wiki#setup-guide) should be updatet to look somthing like this:

To setup VaGABfS, follow the instructions below:
1. Create and update a server
* 1. Create a server with Ubuntu 22.04 LTS
* 2.   Execute: `apt update`
* 3.   Execute: `apt install`
2. Install the required java version
* 1. Execute: `apt install openjdk-18-jre`
3. Install and activate signal-cli
* 1. Execute: `wget https://github.com/AsamK/signal-cli/releases/download/v<version>/signal-cli-<version>.tar.gz` (and replace <version> with current newest version. (see current version under https://github.com/AsamK/signal-cli/releases))
* 2. Execute: `sudo tar xf signal-cli-<version>.tar.gz -C /opt` (and replace <version> with current newest version. (see current version under https://github.com/AsamK/signal-cli/releases))
* 3. Execute: `sudo ln -sf /opt/signal-cli-<version>/bin/signal-cli /usr/local/bin/` (and replace <version> with current newest version. (see current version under https://github.com/AsamK/signal-cli/releases))
* 4. Activate signal-cli (more information about how to activate signal-cli can be found  [here](https://github.com/AsamK/signal-cli/wiki/Quickstart))
4. Download screen
* 1. Execute: `apt install screen`
4. Download VaGABfS
* 1. Execute `git clone https://github.com/The-Bug-Bashers/VaGABfS.git`
* 2. execute `wget https://cdn.pixabay.com/photo/2022/01/30/13/33/github-6980894_1280.png`
6. Finaly start VaGABfS
* 1. Execute`cd VaGABfS`
* 2. Execute `screen bash VaGABfS.sh` 

I thing with this update it will be mouch easyer to get VaGABfS up and running even vor linux newbies.

**Comment by dagadeta** [comment]
Updated [Setup-Guide](https://github.com/The-Bug-Bashers/VaGABfS/wiki#setup-guide) with providing a bash script for not needing to execute every single command separately.
