### ISSUE TITLE
Add whoAreYou Command

### ISSUE THREAD

**Issue by Flottegurke** [The-Bug-Bashers/VaGABfS#2]
It would be great to add an `whoAreYou`-Command so that users can get informations about VaGABfS

**Comment by dagadeta** [comment]
# Suggestion for the text for the command

Hello! I am VaGABfS, the Voting and Group Administration Bot for Signal! It's my job to manage votings in our Signal group and tell you the results. Go to the [Wiki-page of my GitHub-Repository](https://github.com/The-Bug-Bashers/VaGABfS/wiki#commands) (YES, I HAVE A GITHUB REPO AND I'M VERY PROUD OF THAT!!!) to see the commands you can use while chatting with me.

**Comment by Flottegurke** [comment]
Greate Text! The command was added with the proposed text and link preview.
