### ISSUE TITLE
Its Wednesday my dudes <3

### ISSUE THREAD

**Issue by Dinkelbroetchen** [The-Bug-Bashers/VaGABfS#23]
Please create a code which sends a picture of a „german frog“ which sais „Es ist Mittwoch meine Kerle“ which it does every wednesday morning (00:01 AM).
URL: [Es ist Mittwoch meine Kerle](https://ams1.startpage.com/av/anon-image?piurl=https%3A%2F%2Fi.redd.it%2Fthsrb5is0xtz.jpg&sp=1708603638Tccdf2952deecdc46d398ba04bfbb97d8cacdaf06695f52063b9ca652baed8a53)

Plz understand, that my English sucks
Mit freundlichen Grüßen 
Dinkelbroetchen :)

**Comment by Flottegurke** [comment]
I am going to add that to the already existing auto-reply funktion.

- [ ] add germanFrog auto-reply
- [ ] update wiki

**Comment by Flottegurke** [comment]
the url provided did not work i'll use [URL](https://www.reddit.com/media?url=https%3A%2F%2Fpreview.redd.it%2Fmittwoch-meine-freunde-v0-trc4iezxlkfb1.jpg%3Fauto%3Dwebp%26s%3Dec4fa02d32058bae9bae65c3d7c1835a16eac4db) instead

**Comment by Flottegurke** [comment]
@Dinkelbroetchen the immage you provided does'n work please chose a picture out of these:
1. [Picture 1](https://i.seadn.io/gae/SSbzU7aWt3WtZYkLPWo2chdXHr75XIjNLBijXTllHCI3jVZyqN7-4VbmuxaSzRZv7T1kiz1jXcT4jnTBjR2l0-vs3GLS7yOPFT4LNw?auto=format&dpr=1&w=3840)
2.  [Picture 2](https://image.spreadshirtmedia.net/image-server/v1/compositions/T1089A231PA4283PT17X39Y21D195414238W5732H5636/views/1,width=550,height=550,appearanceId=231,backgroundColor=CBCBCB,noPt=true/es-ist-mittwoch-meine-kerle-frosch-meme-its-beanie.jpg) 
3. [Picture 3](https://ih1.redbubble.net/image.3685059110.4371/raf,360x360,075,t,fafafa:ca443f4786.jpg) 
4.  [Picture 4](https://image.spreadshirtmedia.net/image-server/v1/compositions/T631A2PA4699PT17X21Y40D195414238W24787H24372/views/1,width=550,height=550,appearanceId=2,backgroundColor=000000,noPt=true/es-ist-mittwoch-meine-kerle-frosch-meme-its-frauen-t-shirt.jpg)
5. [Picture 5](https://d2j6dbq0eux0bg.cloudfront.net/images/77605319/3165655052.jpg)

I think picture 5 is the best.

**Comment by Flottegurke** [comment]
[Picture 4](https://d2j6dbq0eux0bg.cloudfront.net/images/77605319/3165655052.jpg) could be send using `signal-cli send -geVKi/98VxZfkqRHSt83zbEHJbn/eq3H0a/pIrpV7myA= -a3165655052.jpg`

**Comment by Dinkelbroetchen** [comment]
Picture 4 is fine. You can use that one
