### ISSUE TITLE
Add a Setup-Guide to the wiki

### ISSUE THREAD

**Issue by Flottegurke** [The-Bug-Bashers/VaGABfS#7]
It would be helpful to provide a setup-guide in the wiki.

**Comment by dagadeta** [comment]
* install and activate signal-cli (https://github.com/AsamK/signal-cli/wiki/Quickstart)
* download and start VaGABfS.sh from our Repository

**Comment by dagadeta** [comment]
Added Setup-Guide to the Wiki
